version: "2.0"

services:
  web:
    image: "eceakash/ampableteddygame:latest"  # Replace with your Docker image name
    expose:
      - port: 80
        as: 80
        to:
          - global: true

profiles:
  compute:
    web:
      resources:
        cpu:
          units: 1
        memory:
          size: 512Mi
        storage:
          size: 1Gi
  placement:
    akash:
      attributes:
        region: "global"
      pricing:
        web:
          denom: uakt
          amount: 100

deployment:
  web:
    akash:
      profile: web
      count: 1
